byte byteVar = 254;
short shortVar = 32_757;
int intVar = 2_147_483_617;
long longVar = 9_223_372_031_854_775_807;
char charVar = '=';
float floatVar = 63.161f;
decimal decimalVar = 18511.5146m;
sbyte sbyteVar = -121;
ushort ushortVar = 61535;
uint uintVar = 1_294_967_295;
ulong ulongVar = 11_446_744_073_709_551_615;
string stringVar = ("This is also a string!");
double doubleVar = 1.65;
bool boolVar = false;
Console.WriteLine("The value of byteVar is: {0}", byteVar);
Console.WriteLine("The value of shortVar is: {0}", shortVar);
Console.WriteLine("The value of intVar is: {0}", intVar);
Console.WriteLine("The value of longVar is: {0}", longVar);
Console.WriteLine("The value of charVar is: {0}", charVar);
Console.WriteLine("The value of floarVar is: {0}", floatVar);
Console.WriteLine("The value of decimalVar is: {0}", decimalVar);
Console.WriteLine("The value of sbyteVar is: {0}", sbyteVar);
Console.WriteLine("The value of ushortVar is: {0}", ushortVar);
Console.WriteLine("The value of uintVar is: {0}", uintVar);
Console.WriteLine("The value of ulongVar is: {0}", ulongVar);
Console.WriteLine("The value of stringVar is: {0}", stringVar);
Console.WriteLine("The value of doubleVar is: {0}", doubleVar);
Console.WriteLine("The value of boolVar is: {0}", boolVar);